# Generated by Django 4.2.18 on 2025-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivomaiz',
            name='ID_LOTE',
            field=models.BigIntegerField(default=3734, verbose_name='ID Lote'),
        ),
    ]
