from django import forms
from .models import CultivoMaiz
from constants import CONSTANTES
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class DatosPrediccionForm(forms.ModelForm):
    class Meta:
        model = CultivoMaiz
        fields = [
            "ID_LOTE",
            "TIPO_SIEMBRA",
            "SEM_TRATADAS",
            "MATERIAL_GENETICO",
            "CULT_ANT",
            "DRENAJE",
            "METODO_COSECHA",
            "ALMACENAMIENTO_FINCA",
            "DIAS_EN_EMERGER",
            "DIAS_EN_EMERGER_A_FLORECER",
            "DIAS_EN_FLORECER_A_COSECHAR",
            "POBLACION_20DIAS_AJT",
            "ALTURA_LOT",
            "ContEnfQui_Emer_Flor",
            "ContEnfQui_Flor_Cose",
            "ContMalMec_Siem_Emer",
            "ContMalMec_Emer_Flor",
            "ContMalMec_Flor_Cose",
            "ContMalQui_Antes_Siem",
            "ContMalQui_Siem_Emer",
            "ContMalQui_Emer_Flor",
            "ContMalQui_Flor_Cose",
            "ContPlaQui_Antes_Siem",
            "ContPlaQui_Siem_Emer",
            "ContPlaQui_Emer_Flor",
            "ContPlaQui_Flor_Cose",
            "TotN_Antes_Siem",
            "TotN_Siem_Emer",
            "TotN_Emer_Flor",
            "TotP_Antes_Siem",
            "TotP_Siem_Emer",
            "TotP_Emer_Flor",
            "TotK_Antes_Siem",
            "TotK_Siem_Emer",
            "TotK_Emer_Flor",
            "FerOrg_Emer_Flor",
            "FerQui_Antes_Siem",
            "FerQui_Siem_Emer",
            "FerQui_Emer_Flor",
            "PENDIENTE_RASTA",
            "TERRENO_CIRCUN_RASTA",
            "POSICION_PERFIL_RASTA",
            "NO_CAPAS_RASTA",
            "PH_RASTA",
            "PEDREG_PERFIL_ROCAS",
            "CAP_ENDURE_RASTA",
            "PROFUND_CAP_ENDURE_RASTA",
            "ESPESOR_CAP_ENDURE_RASTA",
            "MOTEADOS_RASTA",
            "PROFUND_MOTEADOS_RASTA",
            "MOTEADOS_MAS70cm_RASTA",
            "ESTRUCTURA_RASTA",
            "OBSERVA_EROSION_RASTA",
            "OBSERVA_MOHO_RASTA",
            "OBSERVA_COSTRAS_DURAS_RASTA",
            "SITIO_EXPUESTO_SOL_RASTA",
            "OBSERVA_COSTRAS_BLANCAS_RASTA",
            "OBSERVA_COSTAS_NEGRAS_RASTA",
            "REGION_SECA_ARIDA_RASTA",
            "OBSERVA_RAICES_VIVAS_RASTA",
            "PROFUND_RAICES_VIVAS_RASTA",
            "OBSERVA_PLANTAS_PEQUENAS_RASTA",
            "OBSERVA_HOJARASCA_MO_RASTA",
            "SUELO_NEGRO_BLANDO_RASTA",
            "CUCHILLO_PRIMER_HTE_RASTA",
            "CERCA_RIOS_QUEBRADAS_RASTA",
            "RECUBRIMIENTO_VEGETAL_SUELO_RASTA",
            "prof_efectiva",
            "d_interno",
            "drenaje_externo",
            "Porc_A",
            "Porc_Ar",
            "Porc_ArA",
            "Porc_ArL",
            "Porc_FrL",
            "Porc_L",
            "Porc_F",
            "porc_x",
            "porc_y",
            "Porc_AF",
            "Porc_BLANDO",
            "Porc_DURO",
            "Porc_EXT_DURO",
            "Porc_FRIABLE",
            "Porc_FIRME",
            "Porc_EXT_FIRME",
            "Porc_PLASTICO",
            "Porc_MUY_PLASTICO",
            "Temp_Max_Avg_Veg",
            "Temp_Min_Avg_Veg",
            "Temp_Avg_Veg",
            "Diurnal_Range_Avg_Veg",
            "Sol_Ener_Accu_Veg",
            "Temp_Max_34_Freq_Veg",
            "Rain_Accu_Veg",
            "Rain_10_Freq_Veg",
            "Rhum_Avg_Veg",
            "Temp_Max_Avg_For",
            "Temp_Min_Avg_For",
            "Temp_Avg_For",
            "Diurnal_Range_Avg_For",
            "Sol_Ener_Accu_For",
            "Temp_Max_34_Freq_For",
            "Rain_Accu_For",
            "Rain_10_Freq_For",
            "Rhum_Avg_For",
            "Temp_Max_Avg_Mad",
            "Temp_Min_Avg_Mad",
            "Temp_Avg_Mad",
            "Diurnal_Range_Avg_Mad",
            "Sol_Ener_Accu_Mad",
            "Temp_Max_34_Freq_Mad",
            "Rain_Accu_Mad",
            "Rain_10_Freq_Mad",
            "Rhum_Avg_Mad"
        ]

    def get_field_groups(self):
        """
        Devuelve una lista de tuplas con el título del grupo y una lista de campos pertenecientes a él.
        """
        return [
            (
                "Variables Generales del Cultivo",
                [
                    self["ID_LOTE"],
                    self["TIPO_SIEMBRA"],
                    self["SEM_TRATADAS"],
                    self["MATERIAL_GENETICO"],
                    self["CULT_ANT"],
                    self["DRENAJE"],
                    self["METODO_COSECHA"],
                    self["ALMACENAMIENTO_FINCA"],
                    self["DIAS_EN_EMERGER"],
                    self["DIAS_EN_EMERGER_A_FLORECER"],
                    self["DIAS_EN_FLORECER_A_COSECHAR"],
                    self["POBLACION_20DIAS_AJT"],
                    self["ALTURA_LOT"],
                ],
            ),
            (
                "Variables de Manejo del Cultivo",
                [
                    self["ContEnfQui_Emer_Flor"],
                    self["ContEnfQui_Flor_Cose"],
                    self["ContMalMec_Siem_Emer"],
                    self["ContMalMec_Emer_Flor"],
                    self["ContMalMec_Flor_Cose"],
                    self["ContMalQui_Antes_Siem"],
                    self["ContMalQui_Siem_Emer"],
                    self["ContMalQui_Emer_Flor"],
                    self["ContMalQui_Flor_Cose"],
                    self["ContPlaQui_Antes_Siem"],
                    self["ContPlaQui_Siem_Emer"],
                    self["ContPlaQui_Emer_Flor"],
                    self["ContPlaQui_Flor_Cose"],
                    self["TotN_Antes_Siem"],
                    self["TotN_Siem_Emer"],
                    self["TotN_Emer_Flor"],
                    self["TotP_Antes_Siem"],
                    self["TotP_Siem_Emer"],
                    self["TotP_Emer_Flor"],
                    self["TotK_Antes_Siem"],
                    self["TotK_Siem_Emer"],
                    self["TotK_Emer_Flor"],
                    self["FerOrg_Emer_Flor"],
                    self["FerQui_Antes_Siem"],
                    self["FerQui_Siem_Emer"],
                    self["FerQui_Emer_Flor"],
                ],
            ),
            (
                "Variables del Suelo",
                [
                    self["PENDIENTE_RASTA"],
                    self["TERRENO_CIRCUN_RASTA"],
                    self["POSICION_PERFIL_RASTA"],
                    self["NO_CAPAS_RASTA"],
                    self["PH_RASTA"],
                    self["PEDREG_PERFIL_ROCAS"],
                    self["CAP_ENDURE_RASTA"],
                    self["PROFUND_CAP_ENDURE_RASTA"],
                    self["ESPESOR_CAP_ENDURE_RASTA"],
                    self["MOTEADOS_RASTA"],
                    self["PROFUND_MOTEADOS_RASTA"],
                    self["MOTEADOS_MAS70cm_RASTA"],
                    self["ESTRUCTURA_RASTA"],
                    self["OBSERVA_EROSION_RASTA"],
                    self["OBSERVA_MOHO_RASTA"],
                    self["OBSERVA_COSTRAS_DURAS_RASTA"],
                    self["SITIO_EXPUESTO_SOL_RASTA"],
                    self["OBSERVA_COSTRAS_BLANCAS_RASTA"],
                    self["OBSERVA_COSTAS_NEGRAS_RASTA"],
                    self["REGION_SECA_ARIDA_RASTA"],
                    self["OBSERVA_RAICES_VIVAS_RASTA"],
                    self["PROFUND_RAICES_VIVAS_RASTA"],
                    self["OBSERVA_PLANTAS_PEQUENAS_RASTA"],
                    self["OBSERVA_HOJARASCA_MO_RASTA"],
                    self["SUELO_NEGRO_BLANDO_RASTA"],
                    self["CUCHILLO_PRIMER_HTE_RASTA"],
                    self["CERCA_RIOS_QUEBRADAS_RASTA"],
                    self["RECUBRIMIENTO_VEGETAL_SUELO_RASTA"],
                    self["prof_efectiva"],
                    self["d_interno"],
                    self["drenaje_externo"],
                    self["Porc_A"],
                    self["Porc_Ar"],
                    self["Porc_ArA"],
                    self["Porc_ArL"],
                    self["Porc_FrL"],
                    self["Porc_L"],
                    self["Porc_F"],
                    self["porc_x"],
                    self["porc_y"],
                    self["Porc_AF"],
                    self["Porc_BLANDO"],
                    self["Porc_DURO"],
                    self["Porc_EXT_DURO"],
                    self["Porc_FRIABLE"],
                    self["Porc_FIRME"],
                    self["Porc_EXT_FIRME"],
                    self["Porc_PLASTICO"],
                    self["Porc_MUY_PLASTICO"],
                ],
            ),
            (
                "Variables de Clima",
                [
                    self["Temp_Max_Avg_Veg"],
                    self["Temp_Min_Avg_Veg"],
                    self["Temp_Avg_Veg"],
                    self["Diurnal_Range_Avg_Veg"],
                    self["Sol_Ener_Accu_Veg"],
                    self["Temp_Max_34_Freq_Veg"],
                    self["Rain_Accu_Veg"],
                    self["Rain_10_Freq_Veg"],
                    self["Rhum_Avg_Veg"],
                    self["Temp_Max_Avg_For"],
                    self["Temp_Min_Avg_For"],
                    self["Temp_Avg_For"],
                    self["Diurnal_Range_Avg_For"],
                    self["Sol_Ener_Accu_For"],
                    self["Temp_Max_34_Freq_For"],
                    self["Rain_Accu_For"],
                    self["Rain_10_Freq_For"],
                    self["Rhum_Avg_For"],
                    self["Temp_Max_Avg_Mad"],
                    self["Temp_Min_Avg_Mad"],
                    self["Temp_Avg_Mad"],
                    self["Diurnal_Range_Avg_Mad"],
                    self["Sol_Ener_Accu_Mad"],
                    self["Temp_Max_34_Freq_Mad"],
                    self["Rain_Accu_Mad"],
                    self["Rain_10_Freq_Mad"],
                    self["Rhum_Avg_Mad"],
                ],
            ),
        ]
